"""
Runtime loader for the curated Synthea patients.

This is what FastAPI imports at startup. It reads the slim JSON
generated by ``curate.py`` and exposes it as a list of
``PatientSummary`` dictionaries. If the file is missing it returns an
empty list so the engine still starts cleanly — the /demo endpoint will
just return an empty array and the UI will hide the picker.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

_DEFAULT_PATH = Path(__file__).parent / "sample_patients" / "patients.json"


@dataclass
class PatientSummary:
    id: str
    label: str
    bucket: str
    age: int
    sex: str
    postal_code: str
    city: str
    state: str
    active_conditions: List[str]
    active_medications: List[str]
    allergies: List[str]
    last_vitals: Dict[str, Any]
    narrative_seed: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "bucket": self.bucket,
            "age": self.age,
            "sex": self.sex,
            "postal_code": self.postal_code,
            "city": self.city,
            "state": self.state,
            "active_conditions": self.active_conditions,
            "active_medications": self.active_medications,
            "allergies": self.allergies,
            "last_vitals": self.last_vitals,
            "narrative_seed": self.narrative_seed,
        }


_CACHE: Optional[List[PatientSummary]] = None


def _load_from_disk(path: Path = _DEFAULT_PATH) -> List[PatientSummary]:
    if not path.exists():
        return []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    out: List[PatientSummary] = []
    for entry in raw.get("patients") or []:
        try:
            out.append(PatientSummary(
                id=str(entry["id"]),
                label=str(entry.get("label", entry["id"])),
                bucket=str(entry.get("bucket", "unbucketed")),
                age=int(entry.get("age", 0)),
                sex=str(entry.get("sex", "unknown")),
                postal_code=str(entry.get("postal_code", "")),
                city=str(entry.get("city", "")),
                state=str(entry.get("state", "")),
                active_conditions=list(entry.get("active_conditions") or []),
                active_medications=list(entry.get("active_medications") or []),
                allergies=list(entry.get("allergies") or []),
                last_vitals=dict(entry.get("last_vitals") or {}),
                narrative_seed=str(entry.get("narrative_seed", "")),
            ))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def load_demo_patients(*, force_reload: bool = False) -> List[PatientSummary]:
    """Return the curated demo patients, caching the parse for the
    process lifetime."""
    global _CACHE
    if _CACHE is None or force_reload:
        _CACHE = _load_from_disk()
    return _CACHE


def list_demo_patients() -> List[Dict[str, Any]]:
    """JSON-ready list of demo patients for the /demo endpoint."""
    return [p.to_dict() for p in load_demo_patients()]
